# Generated by Django 4.2 on 2024-12-06 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_book_avg_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="user",
        ),
    ]
